### ISSUE TITLE
Option to include both legendary planets

### ISSUE THREAD

**Issue by silenroc1** [shenanigans-be/miltydraft#1]
First of all, thanks a lot for the awesome tool! I already used it to prepare our latest game, and it worked really well. Based on my experiences one small feature request: would it be possible to add an option to include both Primor and Hope's End?

In my opinion having both planets on the map makes the game more interesting and fun, so I didn't want to exclude those already during setup. Even when generating seven slices it seemed, based on my small sample, that having one legendary planet is more common than having both divided among the slices. 

The option to include legendaries and wormholes in the original Milty draft does seem to forces inclusion both legendaries. (Again, based on a few samples I just ran.)

Of course there currently is a work around of just manually generating slices until you have a set that includes both legendary planets, which may take a handful of times. So, I can understand if you leave this request. Anyway, thanks again, and interested to hear if you think this would be a good addition.

**Comment by shenanigans-be** [comment]
Solved with 199fdd1e620cdce54b702a812cfe9663d5aa60b3
