### ISSUE TITLE
24 factions + Keleres

### ISSUE THREAD

**Issue by FSou1** [shenanigans-be/miltydraft#3]
Yesterday, when we drafted with all 24 factions available + Keleres, we ended up with 24 factions in the pool (probably, because 24 is the max value for the number of factions input).

I wish we had all 25 to choose from.

**Comment by shenanigans-be** [comment]
Thanks for letting me know! Fixed in https://github.com/shenanigans-be/miltydraft/commit/df3518f7c5d1d0b15eef3b7122e323edca548b9e
