### ISSUE TITLE
Player 8 cant claim and i should be admin also stuck

### ISSUE THREAD

**Issue by Fredbud** [shenanigans-be/miltydraft#37]
Created a 8 player pok draft, all was going great till we got to player 8. And it is showing he's up but can't select. The players 1,3,5,7 show a button to claim ? But the other 3 and Kyle (#8) show blank (no claim button). But he has tried to claim and I have tried to claim slice, speaker for him but not letting me. I created draft and should be admin. Have accessed it at my work computer and phone. Neither works..  please help
![inbound9047321958924159985](https://github.com/shenanigans-be/miltydraft/assets/167546424/19147755-a0c6-4f3a-922f-ebf722d517be)

**Comment by shenanigans-be** [comment]
Hi!

To start: It seemed like someone had claimed player 8 somewhere already. I've manually "unclaimed" Kyle, for now so you should be all ready to go again!

It's important to remember that claiming (as well as the admin privileges) only work on 1 browser/device. So if you made the draft on your phone, you will only be the admin on your phone. Same with claiming: it works _only_ on the thing you claimed it on. 

Did switching devices cause the loss of the "admin" privileges and the claiming issues? Or did something else go wrong entirely (also possible, the code is far from bulletproof 😅)

**Comment by Fredbud** [comment]
Thanks bud that fixed it we had a great draft experience

Sent via the Samsung Galaxy S22+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fredbud** [comment]
Another 8 player draft , started at my work computer but emailed myself and have been drafting on my phone, now my phone doesn't show option to continue and I also should be moderator

**Comment by Fredbud** [comment]
https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmilty.shenanigans.be%2Fd%2F6682b0c3cd8ad%23&data=05%7C02%7C%7Ca9955d1da01748df294c08dc99d3c8cb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638554382105875787%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Lp%2BNiBM2vYlYWC33E2aMviPLOKkNl%2Bn4RDW7CnMhifI%3D&reserved=0
