### ISSUE TITLE
Supernova Placement Settings & Planet Tiers

### ISSUE THREAD

**Issue by RemoteSalad** [shenanigans-be/miltydraft#4]
Hey, thanks for handling this project.

After a few drafts with my local group recently, we had multiple incidences of supernovas being placed directly in front of home systems (on the path to MR). After the draft order, slices, etc. are revealed it's hard to "fairly" resolve that tile issue with everyone. Would it be possible to have a generation option that prevents supernova tiles being placed in that location?

---
As a separate thing I noticed while checking repo:

In `miltydraft/data/tile-selection.json`, is there a reason for  `System 32`(Dal Bootha, Xxehan) to be in the high tier while `System 34 `(Centauri, Gral)  is mid tier?

I'm adding the json objects to reference, but the short of it is `System 34` has a higher resource total, higher influence total, and a tech specialty. Unless paired planet types or the exploration deck is being weighted, I'm not sure why `32` would be ranked over `34`.

    "32": {
        "type": "blue",
        "wormhole": null,
        "planets": [{
                "name": "Dal Bootha",
                "resources": 0,
                "influence": 2,
                "trait": "cultural",
                "specialty": null,
                "legendary": false
            },
            {
                "name": "Xxehan",
                "resources": 1,
                "influence": 1,
                "trait": "cultural",
                "specialty": null,
                "legendary": false
            }
        ]
    },

        "34": {
        "type": "blue",
        "wormhole": null,
        "planets": [{
                "name": "Centauri",
                "resources": 1,
                "influence": 3,
                "trait": "cultural",
                "specialty": null,
                "legendary": false
            },
            {
                "name": "Gral",
                "resources": 1,
                "influence": 1,
                "trait": "industrial",
                "specialty": "propulsion",
                "legendary": false
            }
        ]
    },

The tiers seem generally accurate and I understand it's hard to have perfect tier categories, but this specific comparison jumped out to me.

Thanks again for the great tool.

**Comment by shenanigans-be** [comment]
Hi @RemoteSalad,
Thanks for reaching out! The tiers are sourced from the original [miltydraft.com](https://miltydraft.com/). I checked the SCPT discord and the current list seems to be the result of some discussion among players and which was then amended to distribute the tiles among the tiers as evenly as possible to maximize the amount of possible tiles generated. Now the max is 12, but if we put 32 in the mid-tier, there's only 11 high-tier ones, so only 11 possible slices. 

While I do agree that this seems incredibly arbitrary, part of the point of the draft is that the slices aren't exactly balanced anyway, so keeping it like this seems OK to me. We're sacrificing a bit of "objective fairness" to maximize player choice.

Ideally we should have some sort of new poll that ranks all the systems, then cuts them up into 3 tiers based on vote count or something but that's maybe too ambitious a project for this kind of app. 😅

**Comment by shenanigans-be** [comment]
Hi! 

I just launched an update that includes the ability to regenerate slices (without having to re-input all the settings). This might help with the issue of these unfair supernovas if you run into it again. I've spun off the tier-list thing into it's own issue for clarity (https://github.com/shenanigans-be/miltydraft/issues/11).
