### ISSUE TITLE
Allow specified draft order

### ISSUE THREAD

**Issue by scottmk** [shenanigans-be/miltydraft#41]
My friends and I have a recurring game, and we'd like to be able to do the draft order based on the outcome of the previous game. So last place gets first draft, first place gets last draft.

This system only allows for random draft order. It would be nice to have a toggle that just uses the order given.

**Comment by scottmk** [comment]
I think I could implement this myself, if you could orient me to where the random draft order happens in the code.

**Comment by shenanigans-be** [comment]
Merged! I tinkered a bit with you PR, basically I switched it around so the "default" order is random, but you can specify it being preset, since that will be the case for the vast majority of drafts. I also moved the checkbox to the advanced settings. 

Thanks for your help!
