### ISSUE TITLE
Feature Request: Summary of legendary planets' abilities on their slice summaries

### ISSUE THREAD

**Issue by scottmk** [shenanigans-be/miltydraft#47]
It would be really nice for a quick summary of a legendary planet's special ability in its slice summary.

For example, for Hope's End, it could simply say, "Place 1 Mech or draw 1 Action Card."

**Comment by MikeMcFall** [comment]
I was looking at how this might be done and came up with 2 options.
1. Update the tile png to contain this text. (This might not be the best look, but it should be fairly easy)
2. Have the hover text for the legendary planet contain the text. This would probably need to be added to tile.json and added to the slice info during generation.
![image](https://github.com/shenanigans-be/miltydraft/assets/31281615/e329ca2e-3426-4834-aeb5-e67277931a13)
