### ISSUE TITLE
Stuck at "Loading" after Draft

### ISSUE THREAD

**Issue by Fabmaszter** [shenanigans-be/miltydraft#57]
We just started our Draft today but neither the first player nor the admin is able to draft anything. After selecting an option and confirming in the pop-up the screen the overlay showing "Loading. Please wait." Never disappears. 
I also tried different browsers, different devices, incognito mode etc.

**Comment by FCRamirez** [comment]
I'm having the same issue with a draft started a couple of weeks ago and have tried the same steps. Also tried starting a new game and encountered the same issue.

**Comment by MikeySteel** [comment]
same issues here

**Comment by FCRamirez** [comment]
I am no expert, but it might be a server side error:

![image](https://github.com/user-attachments/assets/8a5354d1-7d25-42a6-95ae-e3ce477e217e)

**Comment by shenanigans-be** [comment]
Whoops. My bad everyone. Should be fixed now!
